name: ci


env:
  VERSION: v0.893

on:
  push:
    branches: 
      - master
      - main

jobs:
  multi-registries:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.full
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7
          push: true
          tags: |
            friendlyuser/dolwarp:latest
            friendlyuser/dolwarp:v0.893
            ghcr.io/friendlyuser/lwarp_docker:latest
            ghcr.io/friendlyuser/lwarp_docker:v0.893
